name: build_android_kernel

on:
  watch:
    types: [started]
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - name: Make Kernel
      run: |
            cd ~
            sudo curl -sL "https://raw.githubusercontent.com/tanyuanman/build_kernel/master/build_kernel.sh" > build-kernel.sh
            sudo chmod 777 build-kernel.sh
            sudo bash ./build-kernel.sh

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: blu_spark_makiras_modified32.zip
        path: /home/runner/gcc32.tar.gz
